### ISSUE TITLE
Refacto : replace forEach with a map

### ISSUE THREAD

**Issue by PierreLeresteux** [saagie/updatarium#75]
After a review from Igor : 
Updatarium:85

> maybe use a map instead of forEach
> you could return an UpdatariumError.ExitError?, then you can gather all ExitError, with the filterNotNull
> Note: maybe use a Sequence to be lazy, and a fold to deal with the failFast feature 

Changelog:44

> map, and a fold for the failfast case.
> 
> Maybe the code could be written with a tailrec in this situation

**Comment by ilaborie** [comment]
I can help
