### ISSUE TITLE
When update is KO, relaunch update

### ISSUE THREAD

**Issue by guillaumeNaimi** [saagie/updatarium#95]
When the update is KO, updatarium say when you relaunch it that it has already been executed in error and don't relaunch the changeset

**Comment by PierreLeresteux** [comment]
It's the normal behavior for now ...

What do you want ? If the changeset is marked as ERROR, stop the process ?

**Comment by PierreLeresteux** [comment]
This is a normal behavior from my point of view :
- a changeset is marked as FAILED in DB
- in the next run, updatarium should be return an error during the changeset test if already executed and stop its execution with an error code.

That's mean, if a changeset has failed, we need to see in DB the cause, fix it and mark this entry as RESOLVED and restart the update
